### ISSUE TITLE
Insertion Failure in Cuckoo Table with Specific Dataset Sizes

### ISSUE THREAD

**Issue by SaintJackson** [real-world-cryprography/APSU#6]
Hi! I encountered an issue where the receiver side reported the failure indicated by a message about the inability to insert parameters into the cuckoo table.

Successful Test Cases:
(2^18, 2^10, 16M-1024.json)
(2^16, 2^10, 16M-1024.json)

Failing Test Case:
(2^16, 2^12, 16M-1024.json)
(2^18, 2^12, 16M-1024.json)
(2^16, 2^16, 16M-1024.json)
(2^18, 2^16, 16M-1024.json)
(2^20, 2^20, 16M-1024.json)

This issue arises consistently in different _balanced_/_unbalanced_ dataset settings with the configuration 16M-1024.json. 

As I did not find explicit illustration about tuning with JSON parameters, could you please provide more guidance on this matter?

 Best wishes and happy new year!

**Comment by lqvir** [comment]
The naming rules for parameters are as follows:
```
|Sender|-|Receiver|.json
```
**e.g. 16M-1024.json**
- `16M` denotes the max Receiver Set supported by this parameter.
- `1024` denotes the max Sender Set supported by this parameter.
- `-com`, `-cmp` denotes parameters optimized to minimize communication or computation cost.

These parameters are designed by [APSI](https://github.com/microsoft/APSI). You can refer to their PSIParams section for details,  but their behavior in Receiver is closer to our Sender.

Wishing you a joyful and prosperous New Year filled with happiness, success, and all the wonderful things life has to offer! Cheers to a fantastic year ahead!

**Comment by SaintJackson** [comment]
Thank you! Though it seems to be a trick for parameterization, your suggestion is indeed very helpful!
